### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by betterze** [dayu1979/stylegan3encoder#1]
Dear dayu1979,

Thank you for sharing this great implementation, I really like it.

Would you mind telling me how long it takes to train the e4e encoder for stylegan3? Did you try the [restyle](https://github.com/yuval-alaluf/restyle-encoder) encoder? 

Thank you for your help.

Best Wishes,

Alex

**Comment by betterze** [comment]
The model is trained using unaligned FFHQ?

**Comment by dayu1979** [comment]
> Dear dayu1979,
> 
> Thank you for sharing this great implementation, I really like it.
> 
> Would you mind telling me how long it takes to train the e4e encoder for stylegan3? Did you try the [restyle](https://github.com/yuval-alaluf/restyle-encoder) encoder?
> 
> Thank you for your help.
> 
> Best Wishes,
> 
> Alex

 About 48 hours of training，I haven't use restyle

**Comment by dayu1979** [comment]
> The model is trained using unaligned FFHQ?

aligned,origin，scale to 256*256

**Comment by betterze** [comment]
Thx a lot.
